/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;
import Connect.MySQLConnection;
import com.mysql.jdbc.CallableStatement;
import java.util.Calendar;
import java.util.Date;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI-VN
 */
public class User1 extends javax.swing.JFrame {

    /**
     * Creates new form AddCa
     */
    MySQLConnection connection = new MySQLConnection();
    DefaultTableModel tableModel;
    public User1() {
        initComponents();
        tableModel = (DefaultTableModel)Table_Edit.getModel();
        ShowTC_TTCL();
        txtid.setEnabled(false);
        tongxe();
        tongncc();
        tongxuat();
        tongnhap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Edit = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JFormattedTextField();
        txtten = new javax.swing.JFormattedTextField();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        TC_Add = new javax.swing.JButton();
        TC_Delete = new javax.swing.JButton();
        TC_UPdate = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtxe = new javax.swing.JLabel();
        txtxe1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtncc = new javax.swing.JLabel();
        txtxe3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtpn = new javax.swing.JLabel();
        txtxe4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtpx = new javax.swing.JLabel();
        txtxe5 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        Table_Edit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "UserName", "Password"
            }
        ));
        Table_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_EditMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Edit);

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));

        jLabel11.setBackground(new java.awt.Color(102, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID:");

        jLabel3.setBackground(new java.awt.Color(102, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên:");

        jLabel4.setBackground(new java.awt.Color(102, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UserName");

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        txtid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtten.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TC_Add.setBackground(new java.awt.Color(204, 204, 255));
        TC_Add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TC_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/outline_add_black_24dp.png"))); // NOI18N
        TC_Add.setText("Thêm");
        TC_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TC_AddActionPerformed(evt);
            }
        });

        TC_Delete.setBackground(new java.awt.Color(204, 204, 255));
        TC_Delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TC_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/outline_remove_black_24dp.png"))); // NOI18N
        TC_Delete.setText("Xóa");
        TC_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TC_DeleteActionPerformed(evt);
            }
        });

        TC_UPdate.setBackground(new java.awt.Color(204, 204, 255));
        TC_UPdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TC_UPdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/outline_cached_black_24dp.png"))); // NOI18N
        TC_UPdate.setText("Sửa ");
        TC_UPdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TC_UPdateActionPerformed(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(102, 255, 102));
        Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TC_Add)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TC_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TC_UPdate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtten, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtuser)
                            .addComponent(txtpass))))
                .addGap(24, 24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TC_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TC_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TC_UPdate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ACCOUNT");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("THÔNG TIN TÀI KHOẢN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ ACCOUNT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(390, 390, 390))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2416666 (1) (1).png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        txtxe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtxe.setForeground(new java.awt.Color(255, 255, 255));
        txtxe.setText("txtxe");

        txtxe1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtxe1.setForeground(new java.awt.Color(255, 255, 255));
        txtxe1.setText("Tổng số xe hiện có:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtxe1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtxe)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtxe)
                    .addComponent(txtxe1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        txtncc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtncc.setForeground(new java.awt.Color(255, 255, 255));
        txtncc.setText("txtncc");

        txtxe3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtxe3.setForeground(new java.awt.Color(255, 255, 255));
        txtxe3.setText("Tổng số nhà cung cấp hiện có:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtxe3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(txtncc)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtncc)
                    .addComponent(txtxe3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        txtpn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtpn.setForeground(new java.awt.Color(255, 255, 255));
        txtpn.setText("txtpn");

        txtxe4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtxe4.setForeground(new java.awt.Color(255, 255, 255));
        txtxe4.setText("Tổng phiếu nhập hiện có:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtxe4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtpn)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpn)
                    .addComponent(txtxe4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        txtpx.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtpx.setForeground(new java.awt.Color(255, 255, 255));
        txtpx.setText("txtpn");

        txtxe5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtxe5.setForeground(new java.awt.Color(255, 255, 255));
        txtxe5.setText("Tổng phiếu xuất hiện có:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtxe5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtpx)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpx)
                    .addComponent(txtxe5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Key-icon.png"))); // NOI18N
        jToggleButton1.setText("Quản Lý Tổng");
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setOpaque(true);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(51, 51, 51));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Log-Out-icon.png"))); // NOI18N
        jToggleButton2.setText("Đăng Xuất");
        jToggleButton2.setBorderPainted(false);
        jToggleButton2.setOpaque(true);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(120, 120, 120))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(41, 41, 41)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

            public void tongxe()
    {
        try {
            Connection con = connection.ConnectMySQL();
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
            java.sql.Statement s = con.createStatement();
            
            ResultSet rs =s.executeQuery("SELECT COUNT(maoto) as 'tongxe' FROM oto");
            rs.next();

            String tongxe = rs.getString("tongxe");

            txtxe.setText( tongxe);
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    
                public void tongncc()
            {
                try {
                    Connection con = connection.ConnectMySQL();
                    Class.forName("com.mysql.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
                    java.sql.Statement s = con.createStatement();

                    ResultSet rs =s.executeQuery("SELECT COUNT(mancc) as 'tongncc' FROM nhacungcap");
                    rs.next();

                    String tongncc = rs.getString("tongncc");

                    txtncc.setText( tongncc);


                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                public void tongnhap()
            {
                try {
                    Connection con = connection.ConnectMySQL();
                    Class.forName("com.mysql.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
                    java.sql.Statement s = con.createStatement();

                    ResultSet rs =s.executeQuery("SELECT COUNT(sophieunhap) as 'tongpn' FROM chitietphieunhap");
                    rs.next();

                    String tongpn = rs.getString("tongpn");

                    txtpn.setText( tongpn);


                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                
                public void tongxuat()
            {
                try {
                    Connection con = connection.ConnectMySQL();
                    Class.forName("com.mysql.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
                    java.sql.Statement s = con.createStatement();

                    ResultSet rs =s.executeQuery("SELECT COUNT(sophieuxuat) as 'tongpx' FROM chitietphieuxuat");
                    rs.next();

                    String tongpx = rs.getString("tongpx");

                    txtpx.setText( tongpx);


                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

    private void TC_UPdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TC_UPdateActionPerformed
       Connection conn = connection.ConnectMySQL();
        Statement Stmt = null;
        String id = String.valueOf(txtid.getText()).trim();
        String name = String.valueOf(txtten.getText()).trim();
        String user = String.valueOf(txtuser.getText()).trim();
        String pass = String.valueOf(txtpass.getText()).trim();
//        String ngay = String.valueOf(TC_Ngay.getSelectedItem().toString().trim());
//        String thang = String.valueOf(TC_Thang.getSelectedItem().toString().trim());
//        String nam = String.valueOf(TC_Nam.getSelectedItem().toString().trim());
//        String BUOI = String.valueOf(TC_BoxBuoi.getSelectedItem().toString().trim());
//        String buoi = chuyendoiBuoi(BUOI);
//        String ghichu = TC_ghichu.getText();
//        String NgayThang = nam+"-"+thang+"-"+ngay;
//        boolean chekcdate = SauNgayHienTai(Integer.parseInt(ngay) , Integer.parseInt(thang), Integer.parseInt(nam));
        if(id.equals("") || name.equals("")|| user.equals("")|| pass.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đầy đủ thông tin!!!", "Error", 1);
        }else{
            boolean checktrung = true;
            try {

                CallableStatement cSmt1 = (CallableStatement) conn.prepareCall("SELECT `id`, `name`, `tendangnhap`, `matkhau` FROM `dangnhap` where id=? and name=? and tendangnhap=? and matkhau=?");
                cSmt1.setString(1, id);
                cSmt1.setString(2, name);
                cSmt1.setString(3, user);
                cSmt1.setString(4, pass);
                ResultSet rs_checkid = cSmt1.executeQuery();
                if(rs_checkid.next()){
                    JOptionPane.showMessageDialog(rootPane, "Thông tin chưa thay đổi", "Erro", 1);
                    checktrung = false;
                }else{
                    try{
                        
                    Connection con1;
                    PreparedStatement insert;
                    Class.forName("com.mysql.jdbc.Driver");
                    con1 = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
                    insert = con1.prepareStatement("update dangnhap set name= ? , tendangnhap=? , matkhau= ?  where id= ?");
                    insert.setString(1,name);
                    insert.setString(2,user);
                    insert.setString(3,pass);
                    insert.setString(4,id);
                    
                    insert.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Cập Nhật Tài Khoản User thành công");
            
                    txtid.setText("");
                    txtten.setText("");
                    txtuser.setText(""); 
                    txtpass.setText(""); 

                    }catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        ShowTC_TTCL();
    }//GEN-LAST:event_TC_UPdateActionPerformed

    private void Table_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_EditMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel= (DefaultTableModel)Table_Edit.getModel();
        String id = tableModel.getValueAt(Table_Edit.getSelectedRow(), 0).toString();
        String name = tableModel.getValueAt(Table_Edit.getSelectedRow(), 1).toString();
        String user = tableModel.getValueAt(Table_Edit.getSelectedRow(), 2).toString();
        String pass = tableModel.getValueAt(Table_Edit.getSelectedRow(), 3).toString();
        
       
        
        
        txtid.setText(id);
        txtten.setText(name);
        txtuser.setText(user);
        txtpass.setText(pass);
    }//GEN-LAST:event_Table_EditMouseClicked

    private void TC_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TC_DeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table_Edit.getModel();
        int selectedIndex = Table_Edit.getSelectedRow();

        try {
            Connection con1;
            PreparedStatement insert;

            String getmanv = (String) Table_Edit.getValueAt(selectedIndex, 0);

            //int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());

            int dialogResult = JOptionPane.showConfirmDialog (rootPane, "Bạn Có Chắc xóa tài khoản này chứ ?","Cảnh Báo",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                // Saving code here

                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
                insert = con1.prepareStatement("DELETE FROM `dangnhap` WHERE id=?");

                insert.setString(1,getmanv);
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this, "Xóa Tài Khoản thành công");
                //                reset();
                ShowTC_TTCL();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
        }

        ShowTC_TTCL();
    }//GEN-LAST:event_TC_DeleteActionPerformed

    private void TC_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TC_AddActionPerformed
        // TODO add your handling code here:
        Connection con;
        PreparedStatement insert;
        Connection con1;
        ResultSet rs1;

        String id = String.valueOf(txtid.getText()).trim();
        String name = String.valueOf(txtten.getText()).trim();
        String user = String.valueOf(txtuser.getText()).trim();
        String pass = String.valueOf(txtpass.getText()).trim();
        

                if ( name.equals("") || user.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đầy đủ thông tin", "Erro", 1);
        }  else {
            //Thêm thông tin vào database.
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
                    insert = con.prepareStatement("SELECT tendangnhap  FROM `dangnhap` WHERE tendangnhap=? ");
               
                    insert.setString(1, user);
//                    insert.setString(2, pass);
                    ResultSet rs_checkid = insert.executeQuery();
                    while (rs_checkid.next()) {
                        String ma = rs_checkid.getString("tendangnhap");
//                        String pa = rs_checkid.getString("matkhau");
                    if (ma.equals(user) ) {
                        JOptionPane.showMessageDialog(rootPane, "Tài Khoản đã tồn tại! Yêu cầu chọn UserName khác", "Erro", 1);
                    } 
                    }
                }catch (Exception e) {
                e.printStackTrace();
            }
                        try {
                                // TODO add your handling code here:
                                Class.forName("com.mysql.jdbc.Driver");
                                con = DriverManager.getConnection("jdbc:mysql://localhost/car","root","");
                                insert = con.prepareStatement("insert into dangnhap(name,tendangnhap,matkhau)values(?,?,?)");
                                insert.setString(1, name);
                                insert.setString(2, user);
                                insert.setString(3, pass);


                                insert.executeUpdate();
                                JOptionPane.showMessageDialog(rootPane, "Thêm Tài Khoản Thành Công");
                                ShowTC_TTCL();
                                txtten.setText("");
                                txtuser.setText("");
                                txtpass.setText("");
        

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
                
            
        
        
        }
    }//GEN-LAST:event_TC_AddActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        new TrangChu().setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        ShowTC_TTCL();
        tongxe();
        tongncc();
        tongxuat();
        tongnhap();
        txtid.setText("");
        txtten.setText("");
        txtuser.setText("");
        txtpass.setText("");
    }//GEN-LAST:event_ResetActionPerformed
    private void ShowTC_TTCL(){
    DefaultTableModel tableModel= (DefaultTableModel)Table_Edit.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        ResultSet rs = null;
        try {
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("SELECT `id`, `name`, `tendangnhap`, `matkhau` FROM `dangnhap`");
            rs = cStmt.executeQuery();
            while(rs.next()){
                String id = rs.getString("id");
                String name = rs.getString("name");
                String tendn = rs.getString("tendangnhap");
                String mk = rs.getString("matkhau");
//                String dateNS = rs.getString("ngaylam");
//                String NS[] = dateNS.split("-");
//                String ngaylam = NS[2]+"/"+NS[1]+"/"+NS[0];
//                String buoi = rs.getString("buoi");
//                String ghichu = rs.getString("ghichu");
                //String ngaysinh = dateNS.getDay()+"/"+dateNS.getMonth()+""+dateNS.getYear();
                tableModel.addRow(new String[]{id, name, tendn, mk});
            } 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton TC_Add;
    private javax.swing.JButton TC_Delete;
    private javax.swing.JButton TC_UPdate;
    private javax.swing.JTable Table_Edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JFormattedTextField txtid;
    private javax.swing.JLabel txtncc;
    private javax.swing.JTextField txtpass;
    private javax.swing.JLabel txtpn;
    private javax.swing.JLabel txtpx;
    private javax.swing.JFormattedTextField txtten;
    private javax.swing.JTextField txtuser;
    private javax.swing.JLabel txtxe;
    private javax.swing.JLabel txtxe1;
    private javax.swing.JLabel txtxe3;
    private javax.swing.JLabel txtxe4;
    private javax.swing.JLabel txtxe5;
    // End of variables declaration//GEN-END:variables
}
